if(_name == "Reimu")
{
  _spellList.push_back(Spells::GetSpell("Holy Orb"));
  _spellList.push_back(Spells::GetSpell("Radiant Light"));
  _spellList.push_back(Spells::GetSpell("Seal of God"));
  _spellList.push_back(Spells::GetSpell("Blessed Ground"));
  _spellList.push_back(Spells::GetSpell("Barrier of Faith"));
}
else if(_name == "Marisa")
{
  _spellList.push_back(Spells::GetSpell("Magic Missile"));
  _spellList.push_back(Spells::GetSpell("Blind Knowledge"));
  _spellList.push_back(Spells::GetSpell("Distortion Field"));
  _spellList.push_back(Spells::GetSpell("Ravaging Flow"));
  _spellList.push_back(Spells::GetSpell("Mastery of Mind"));
}
else if(_name == "Remilia")
{
  _spellList.push_back(Spells::GetSpell("Demonic Strike"));
  _spellList.push_back(Spells::GetSpell("Curse of the Han'yo"));
  _spellList.push_back(Spells::GetSpell("Embrace of the Demon"));
}
else if(_name == "Sakuya")
{
  _spellList.push_back(Spells::GetSpell("Tickling Needles"));
  _spellList.push_back(Spells::GetSpell("Stabby Stab!"));
  _spellList.push_back(Spells::GetSpell("Sharp Assault"));
  _spellList.push_back(Spells::GetSpell("Blitzkrieg"));
  _spellList.push_back(Spells::GetSpell("Time Bubble"));
}
else if(_name == "Patchouli")
{
  _spellList.push_back(Spells::GetSpell("Extinction"));
  _spellList.push_back(Spells::GetSpell("Icicle Barrage"));
  _spellList.push_back(Spells::GetSpell("Tornado"));
  _spellList.push_back(Spells::GetSpell("Fear of the Dark"));
  _spellList.push_back(Spells::GetSpell("Forbidden Spell #98"));
}
else if(_name == "Chen")
{
  _spellList.push_back(Spells::GetSpell("Quick Surprise"));
  _spellList.push_back(Spells::GetSpell("Expect the Unexpected"));
  _spellList.push_back(Spells::GetSpell("Untouchable"));
  _spellList.push_back(Spells::GetSpell("True Form"));
}
else if(_name == "Meirin")
{
  _spellList.push_back(Spells::GetSpell("Holy Punch"));
  _spellList.push_back(Spells::GetSpell("Stonebreaker"));
  _spellList.push_back(Spells::GetSpell("Healing Rain"));
  _spellList.push_back(Spells::GetSpell("Cleanse"));
}
else if(_name == "Cirno")
{
  _spellList.push_back(Spells::GetSpell("Breath of the Baby Ice Dragon"));
  _spellList.push_back(Spells::GetSpell("Ice Prison"));
  _spellList.push_back(Spells::GetSpell("Blizzard of the Tundra Wasteland"));
  _spellList.push_back(Spells::GetSpell("Frozen Blood"));
}
else if(_name == "Minoriko")
{
  _spellList.push_back(Spells::GetSpell("Leavecutter"));
  _spellList.push_back(Spells::GetSpell("Raging Storm"));
  _spellList.push_back(Spells::GetSpell("Blessing of the Wind God"));
  _spellList.push_back(Spells::GetSpell("Second Wind"));
}
else if(_name == "Youmu")
{
  _spellList[1] = Spells::GetSpell("Meditation");
  _spellList.push_back(Spells::GetSpell("Alpha Slash"));
  _spellList.push_back(Spells::GetSpell("Omega Slash"));
  _spellList.push_back(Spells::GetSpell("Supersonic Slash"));
  _spellList.push_back(Spells::GetSpell("Omni Slash"));
}
else if(_name == "Alice")
{
  _spellList.push_back(Spells::GetSpell("Stun Bomb"));
  _spellList.push_back(Spells::GetSpell("Magic Sap"));
  _spellList.push_back(Spells::GetSpell("Thousand Needles"));
  _spellList.push_back(Spells::GetSpell("Empowering Laser"));
}
else if(_name == "Rumia")
{
  _spellList.push_back(Spells::GetSpell("Shadow Ray"));
  _spellList.push_back(Spells::GetSpell("Dark Fog (Enemy)"));
  _spellList.push_back(Spells::GetSpell("Dark Fog (Ally)"));
}
else if(_name == "Wriggle")
{
  _spellList.push_back(Spells::GetSpell("Deadly Venom"));
  _spellList.push_back(Spells::GetSpell("Deadly Swarm"));
  _spellList.push_back(Spells::GetSpell("Bug Storm"));
}
else if(_name == "Yuugi")
{
  _spellList.push_back(Spells::GetSpell("Beastly Smash"));
  _spellList.push_back(Spells::GetSpell("Shadow Trap"));
  _spellList.push_back(Spells::GetSpell("Summon Storm"));
  _spellList.push_back(Spells::GetSpell("Fiery Fury Fist"));
}
else if(_name == "Aya")
{
  _spellList.push_back(Spells::GetSpell("Wind Strike"));
  _spellList.push_back(Spells::GetSpell("Storm Dash"));
  _spellList.push_back(Spells::GetSpell("Sharing is caring"));
  _spellList.push_back(Spells::GetSpell("Embrace of the Wind God"));
}
else if(_name == "Iku")
{
  _spellList.push_back(Spells::GetSpell("Melting Thunder"));
  _spellList.push_back(Spells::GetSpell("Violent Thunderstorm"));
  _spellList.push_back(Spells::GetSpell("Surge of Lightning"));
  _spellList.push_back(Spells::GetSpell("Hurricane"));
}
else if(_name == "Komachi")
{
  _spellList.push_back(Spells::GetSpell("Scythe of the Doomed"));
  _spellList.push_back(Spells::GetSpell("Freeze Them To Death!"));
  _spellList.push_back(Spells::GetSpell("Fuck Them Up!"));
  _spellList.push_back(Spells::GetSpell("Omae Wa Mo Shindeiru"));
  _spellList.push_back(Spells::GetSpell("Ghost Nova"));
}
else if(_name == "Suwako")
{
  _spellList.push_back(Spells::GetSpell("Glimmering Trap"));
  _spellList.push_back(Spells::GetSpell("Tsunami"));
  _spellList.push_back(Spells::GetSpell("Jumping Jacks"));
  _spellList.push_back(Spells::GetSpell("Wave of Darkness"));
}
else if(_name == "Sanae")
{
  _spellList.push_back(Spells::GetSpell("Holy Entanglement"));
  _spellList.push_back(Spells::GetSpell("Hidden Seal #37"));
  _spellList.push_back(Spells::GetSpell("Divine Restoration"));
  _spellList.push_back(Spells::GetSpell("Miracle Poke"));
}
else if(_name == "Nitori")
{
  _spellList.push_back(Spells::GetSpell("Waterfall X84"));
  _spellList.push_back(Spells::GetSpell("Amazing Bitchslap X11"));
  _spellList.push_back(Spells::GetSpell("Optical Camouflage X69"));
  _spellList.push_back(Spells::GetSpell("5 ExaWatts Extermination Laser X1337"));
}
else if(_name == "Ran")
{
  _spellList.push_back(Spells::GetSpell("8 Headed Radiant Hydra"));
  _spellList.push_back(Spells::GetSpell("Mystical Dragonfly"));
  _spellList.push_back(Spells::GetSpell("Balance Is Key"));
  _spellList.push_back(Spells::GetSpell("Defense of the Ancients"));
  _spellList.push_back(Spells::GetSpell("Offense of the Ancients"));
}
else if(_name == "Udonge")
{
  _spellList.push_back(Spells::GetSpell("Fractured Laser Barrage"));
  _spellList.push_back(Spells::GetSpell("Mind Storm"));
  _spellList.push_back(Spells::GetSpell("Weakening Fire Beam"));
  _spellList.push_back(Spells::GetSpell("Orb of Filth"));
  _spellList.push_back(Spells::GetSpell("The Alchemists Secret Elixir"));
}
else if(_name == "Eirin")
{
  _spellList.push_back(Spells::GetSpell("Forbidden Spell #42"));
  _spellList.push_back(Spells::GetSpell("Acidic Sea"));
  _spellList.push_back(Spells::GetSpell("Magic-Dampening Zone"));
  _spellList.push_back(Spells::GetSpell("Grand Healing Potion"));
  _spellList.push_back(Spells::GetSpell("Twisting Nether"));
}
else if(_name == "Tenko")
{
  _spellList.push_back(Spells::GetSpell("Secret Technique #48"));
  _spellList.push_back(Spells::GetSpell("Secret Technique #64"));
  _spellList.push_back(Spells::GetSpell("Secret Technique #76"));
  _spellList.push_back(Spells::GetSpell("Secret Technique: Stoneform"));
}
else if(_name == "Mokou")
{
  _spellList.push_back(Spells::GetSpell("Flying Phoenix"));
  _spellList.push_back(Spells::GetSpell("Raging Firestorm"));
  _spellList.push_back(Spells::GetSpell("Forbidden Spell #64"));
  _spellList.push_back(Spells::GetSpell("Rise of the Phoenix"));
}
else if(_name == "Flandre")
{
  _spellList.push_back(Spells::GetSpell("Reckless Swing"));
  _spellList.push_back(Spells::GetSpell("Forbidden Technique: Rage"));
  _spellList.push_back(Spells::GetSpell("Ultimate Taboo"));
}
else if(_name == "Rin")
{
  _spellList.push_back(Spells::GetSpell("Catwalk"));
  _spellList.push_back(Spells::GetSpell("Vengeful Spirit"));
  _spellList.push_back(Spells::GetSpell("Needle Rain"));
  _spellList.push_back(Spells::GetSpell("Fire Wheel"));
}
else if(_name == "Suika")
{
  _spellList.push_back(Spells::GetSpell("Penetrating Horn"));
  _spellList.push_back(Spells::GetSpell("Mini Black Hole"));
  _spellList.push_back(Spells::GetSpell("Fuzzy Overhaul"));
  _spellList.push_back(Spells::GetSpell("Hidden Power"));
  _spellList.push_back(Spells::GetSpell("One At A Time"));
}
else if(_name == "Yuyuko")
{
  _spellList.push_back(Spells::GetSpell("Haunt"));
  _spellList.push_back(Spells::GetSpell("Seed of Corruption"));
  _spellList.push_back(Spells::GetSpell("Ghost Nova"));
  _spellList.push_back(Spells::GetSpell("Hand of Death"));
}
else if(_name == "Kaguya")
{
  _spellList.push_back(Spells::GetSpell("Anomaly"));
  _spellList.push_back(Spells::GetSpell("Blessing of the Gods"));
  _spellList.push_back(Spells::GetSpell("Piercing Flames"));
  _spellList.push_back(Spells::GetSpell("Darkness Comes From Within"));
  _spellList.push_back(Spells::GetSpell("Divine Light of the Goddess"));
}
else if(_name == "Yukari")
{
  _spellList.push_back(Spells::GetSpell("Light and Shadow Intertwined"));
  _spellList.push_back(Spells::GetSpell("Miniature Tornado"));
  _spellList.push_back(Spells::GetSpell("Last Man Standing"));
  _spellList.push_back(Spells::GetSpell("Let's speed this up"));
  _spellList.push_back(Spells::GetSpell("Twilight Barrier"));
}
else if(_name == "Kourin")
{
  _spellList.push_back(Spells::GetSpell("Scarlet Sword Slash"));
  _spellList.push_back(Spells::GetSpell("Inspiring Speech"));
  _spellList.push_back(Spells::GetSpell("Night Stalker"));
  _spellList.push_back(Spells::GetSpell("Explosive Fist"));
  _spellList.push_back(Spells::GetSpell("Technique #10"));
}
else if(_name == "Renko")
{
  _spellList.push_back(Spells::GetSpell("Timestop"));
  _spellList.push_back(Spells::GetSpell("Blood for Power"));
  _spellList.push_back(Spells::GetSpell("Crippling Aura"));
}
else if(_name == "Maribel")
{
  _spellList.push_back(Spells::GetSpell("Chaos Barrier"));
  _spellList.push_back(Spells::GetSpell("Cataclysmic Barrier"));
  _spellList.push_back(Spells::GetSpell("Balance Strike"));
  _spellList.push_back(Spells::GetSpell("Wind Slash"));
  _spellList.push_back(Spells::GetSpell("True Potential"));
}
else if(_name == "Utsuho")
{
  _spellList.push_back(Spells::GetSpell("Hellfire Flare"));
  _spellList.push_back(Spells::GetSpell("Nuclear Meltdown"));
  _spellList.push_back(Spells::GetSpell("Hell's Inferno"));
}
else if(_name == "Kanako")
{
  _spellList.push_back(Spells::GetSpell("Demonic Seal 61: Maru"));
  _spellList.push_back(Spells::GetSpell("Forbidden Spell #74"));
  _spellList.push_back(Spells::GetSpell("Frost Blast"));
  _spellList.push_back(Spells::GetSpell("Wind God Tornado"));
}
else if(_name == "Yuuka")
{
  _spellList.push_back(Spells::GetSpell("Shadow Shot"));
  _spellList.push_back(Spells::GetSpell("Dark Mend"));
  _spellList.push_back(Spells::GetSpell("Chaos Cleanse"));
  _spellList.push_back(Spells::GetSpell("Ragnarǫk"));
}
else if(_name == "Mystia")
{
  _spellList.push_back(Spells::GetSpell("Quick Dive"));
  _spellList.push_back(Spells::GetSpell("Poison Flight"));
  _spellList.push_back(Spells::GetSpell("Offense Is The Best Defense"));
  _spellList.push_back(Spells::GetSpell("Cleansing Song"));
}
else if(_name == "Keine")
{
  _spellList.push_back(Spells::GetSpell("The Old Ways"));
  _spellList.push_back(Spells::GetSpell("The New Ways"));
  _spellList.push_back(Spells::GetSpell("Support Technique: Sword"));
  _spellList.push_back(Spells::GetSpell("Support Technique: Wand"));
  _spellList.push_back(Spells::GetSpell("Support Technique: Shield"));
}
else if(_name == "Utsuho")
{
  _spellList.push_back(Spells::GetSpell("Hellfire Flare"));
  _spellList.push_back(Spells::GetSpell("Nuclear Meltdown"));
  _spellList.push_back(Spells::GetSpell("Hell's Inferno"));
}
else if(_name == "Eiki")
{
  for(int i = 0; i < 5; ++i)
    _spellList.push_back(Spells::GetRandomSpell());
}
