if(_name == "Reimu")
{
  _spellList.push_back(Spells::GetSpell("Holy Orb"));
  _spellList.push_back(Spells::GetSpell("Radiant Light"));
  _spellList.push_back(Spells::GetSpell("Seal of God"));
  _spellList.push_back(Spells::GetSpell("Blessed Ground"));
  _spellList.push_back(Spells::GetSpell("Barrier of Faith"));
}
else if(_name == "Marisa")
{
  _spellList.push_back(Spells::GetSpell("Magic Missile"));
  _spellList.push_back(Spells::GetSpell("Arcane Barrage"));
  _spellList.push_back(Spells::GetSpell("Distortion Field"));
  _spellList.push_back(Spells::GetSpell("Ravaging Flow"));
  _spellList.push_back(Spells::GetSpell("Mastery of Mind"));
}
else if(_name == "Remilia")
{
  _spellList.push_back(Spells::GetSpell("Demonic Strike"));
  _spellList.push_back(Spells::GetSpell("Curse of the Han'yō"));
  _spellList.push_back(Spells::GetSpell("Embrace of the Demon"));
}
else if(_name == "Sakuya")
{
  _spellList.push_back(Spells::GetSpell("Tickling Needles"));
  _spellList.push_back(Spells::GetSpell("Stabby Stab!"));
  _spellList.push_back(Spells::GetSpell("Sharp Assault"));
  _spellList.push_back(Spells::GetSpell("Accelerate Time"));
  _spellList.push_back(Spells::GetSpell("Time Bubble"));
}
else if(_name == "Patchouli")
{
  _spellList.push_back(Spells::GetSpell("Extinction"));
  _spellList.push_back(Spells::GetSpell("Icicle Barrage"));
  _spellList.push_back(Spells::GetSpell("Tornado"));
  _spellList.push_back(Spells::GetSpell("Fear of the Dark"));
  _spellList.push_back(Spells::GetSpell("Forbidden Spell #19"));
}
else if(_name == "Chen")
{
  _spellList.push_back(Spells::GetSpell("Quick Surprise"));
  _spellList.push_back(Spells::GetSpell("Expect the Unexpected"));
  _spellList.push_back(Spells::GetSpell("Untouchable"));
  _spellList.push_back(Spells::GetSpell("True Form"));
}
else if(_name == "Meirin")
{
  _spellList.push_back(Spells::GetSpell("Holy Punch"));
  _spellList.push_back(Spells::GetSpell("Stonebreaker"));
  _spellList.push_back(Spells::GetSpell("Healing Rain"));
  _spellList.push_back(Spells::GetSpell("Cleanse"));
}
else if(_name == "Cirno")
{
  _spellList.push_back(Spells::GetSpell("Breath of the Baby Ice Dragon"));
  _spellList.push_back(Spells::GetSpell("Ice Prison"));
  _spellList.push_back(Spells::GetSpell("Blizzard of the Tundra Wasteland"));
  _spellList.push_back(Spells::GetSpell("Frozen Blood"));
}
else if(_name == "Minoriko")
{
  _spellList.push_back(Spells::GetSpell("Leavecutter"));
  _spellList.push_back(Spells::GetSpell("Raging Storm"));
  _spellList.push_back(Spells::GetSpell("Blessing of the Wind God"));
  _spellList.push_back(Spells::GetSpell("Second Wind"));
}
else if(_name == "Youmu")
{
  _spellList.push_back(Spells::GetSpell("Alpha Slash"));
  _spellList.push_back(Spells::GetSpell("Omega Slash"));
  _spellList.push_back(Spells::GetSpell("Supersonic Slash"));
  _spellList.push_back(Spells::GetSpell("Omni Slash"));
}
else if(_name == "Alice")
{
  _spellList.push_back(Spells::GetSpell("Stun Bomb"));
  _spellList.push_back(Spells::GetSpell("Magic Sap"));
  _spellList.push_back(Spells::GetSpell("Thousand Needles"));
  _spellList.push_back(Spells::GetSpell("Empowering Laser"));
}
else if(_name == "Rumia")
{
  _spellList.push_back(Spells::GetSpell("Shadow Ray"));
  _spellList.push_back(Spells::GetSpell("Dark Fog (Enemy)"));
  _spellList.push_back(Spells::GetSpell("Dark Fog (Ally)"));
}
else if(_name == "Wriggle")
{
  _spellList.push_back(Spells::GetSpell("Deadly Venom"));
  _spellList.push_back(Spells::GetSpell("Deadly Swarm"));
  _spellList.push_back(Spells::GetSpell("Bug Storm"));
}
else if(_name == "Yuugi")
{
  _spellList.push_back(Spells::GetSpell("Beastly Smash"));
  _spellList.push_back(Spells::GetSpell("Shadow Trap"));
  _spellList.push_back(Spells::GetSpell("Sumon Storm"));
  _spellList.push_back(Spells::GetSpell("Fiery Fury Fist"));
}
else if(_name == "Aya")
{
  _spellList.push_back(Spells::GetSpell("Wind Strike"));
  _spellList.push_back(Spells::GetSpell("Storm Dash"));
  _spellList.push_back(Spells::GetSpell("Sumon Storm"));
  _spellList.push_back(Spells::GetSpell("Fiery Fury Fist"));
}
